name: Sample NPM Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm test

      - name: Create Artifact
        run: |
          mkdir dist
          cp -r * dist/
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: dist/
