name: Pre-commit Hook

on:
  push:
    branches:
      - main

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Linter
        run: npm install -g your-linter

      - name: Run Styling Check
        run: your-linter check
