name: Run Unit Tests
on:
  workflow_run:
    workflows: ["NPM Build and Test"]
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Jest Tests
        run: npm test
